/**
 * Export the live model to a real .xlsx workbook (SheetJS, loaded on demand).
 *
 * This writes a LIVE model, not a snapshot: the Assumptions sheet holds the input
 * cells and every other sheet references them with real Excel formulas. Change a
 * growth rate in Excel and the statements, DCF and value per share all recalculate —
 * exactly like a model built by hand.
 *
 * All monetary values are in millions of the reporting currency, matching the app.
 */
const r1 = (v) => (typeof v === "number" && isFinite(v) ? Math.round(v * 10) / 10 : v);
const r4 = (v) => (typeof v === "number" && isFinite(v) ? Math.round(v * 10000) / 10000 : v);

// 0 -> A, 1 -> B ...
const col = (i) => {
  let s = "";
  for (let n = i; n >= 0; n = Math.floor(n / 26) - 1) { s = String.fromCharCode(65 + (n % 26)) + s; }
  return s;
};

const PCT = "0.0%";
const NUM = "#,##0.0";
const MULT = '0.00"x"';

export async function exportModelXlsx(state, R, cur = "$", scenName = "Base") {
  const XLSX = await import("xlsx");
  const h = state.hist, a = state.asm, f = R.base.f, d = R.base.dcf;
  const L = h.rev.length - 1;
  const nH = h.rev.length;            // historical year count
  const nF = 5;                       // forecast years
  const c0 = 1;                       // first historical column (B)
  const fc0 = c0 + nH;                // first forecast column
  const lastHistCol = col(fc0 - 1);

  const wb = XLSX.utils.book_new();
  const setF = (ws, addr, formula, z) => { ws[addr] = { t: "n", f: formula, ...(z ? { z } : {}) }; };
  const setV = (ws, addr, v, z) => { ws[addr] = { t: "n", v: typeof v === "number" && isFinite(v) ? v : 0, ...(z ? { z } : {}) }; };

  /* ---------------- 1. ASSUMPTIONS (the only cells you edit) ---------------- */
  const A = {                     // 1-indexed Excel rows
    growth: 5, gm: 6, opex: 7, da: 8, capex: 9, tax: 10,
    ar: 13, inv: 14, oca: 15, ap: 16, accr: 17, ocl: 18,
    rf: 21, beta: 22, erp: 23, kd: 24, tg: 25, exit: 26,
    shares: 29, price: 30, debt: 31, cash: 32,
  };
  const aRows = [
    [`${h.name} (${h.symbol}) — ASSUMPTIONS`],
    [`${scenName} case · figures in ${h.currency} millions · generated by Vexa`],
    ["Edit any value in column B — every other sheet recalculates automatically."],
    ["OPERATING", "Value"],
    ["Revenue growth (annual)", r4(a.growth[0])],
    ["Gross margin", r4(a.gm[0])],
    ["Operating costs % of revenue", r4(a.sgaPct[0])],
    ["D&A % of revenue", r4(a.daPct)],
    ["Capex % of revenue", r4(a.capexPct)],
    ["Tax rate", r4(a.taxRate)],
    [],
    ["WORKING CAPITAL", "Value"],
    ["Accounts receivable % of revenue", r4(a.arPct)],
    ["Inventory % of cost of revenue", r4(a.invPct)],
    ["Other current assets % of revenue", r4(a.ocaPct)],
    ["Accounts payable % of cost of revenue", r4(a.apPct)],
    ["Accrued expenses % of revenue", r4(a.accrPct)],
    ["Other current liabilities % of revenue", r4(a.oclPct)],
    [],
    ["VALUATION", "Value"],
    ["Risk-free rate", r4(a.rf)],
    ["Beta", r4(a.beta)],
    ["Equity risk premium", r4(a.erp)],
    ["Cost of debt (pre-tax)", r4(a.kd)],
    ["Terminal growth", r4(a.tg)],
    ["Exit EV/EBITDA multiple", r1(a.exitMult)],
    [],
    ["CAPITAL STRUCTURE (from filings)", "Value"],
    ["Diluted shares outstanding (M)", r1(h.shares[L])],
    ["Share price", r4(h.price)],
    ["Total debt", r1(h.debt[L])],
    ["Cash & equivalents", r1(h.cash[L])],
  ];
  const wsA = XLSX.utils.aoa_to_sheet(aRows);
  wsA["!cols"] = [{ wch: 40 }, { wch: 14 }];
  [A.growth, A.gm, A.opex, A.da, A.capex, A.tax, A.ar, A.inv, A.oca, A.ap, A.accr, A.ocl,
   A.rf, A.erp, A.kd, A.tg].forEach((r) => { if (wsA["B" + r]) wsA["B" + r].z = PCT; });
  if (wsA["B" + A.exit]) wsA["B" + A.exit].z = MULT;
  [A.shares, A.debt, A.cash].forEach((r) => { if (wsA["B" + r]) wsA["B" + r].z = NUM; });
  XLSX.utils.book_append_sheet(wb, wsA, "Assumptions");

  const AS = (row) => `Assumptions!$B$${row}`;

  /* ---------------- 2. MODEL (history as values, forecast as formulas) ---------------- */
  const M = {
    rev: 4, cogs: 5, gp: 6, opex: 7, ebit: 8, da: 9, ebitda: 10, taxOnEbit: 11, nopat: 12, capex: 13,
    ar: 16, inv: 17, oca: 18, ap: 19, accr: 20, ocl: 21, nwc: 22, dnwc: 23, ufcf: 25,
  };
  const header = ["Line item", ...(h.years || []).map(String), ...Array.from({ length: nF }, (_, i) => `Forecast ${i + 1}`)];
  const blank = new Array(header.length).fill(null);
  const mRows = [
    [`${h.name} — 3-STATEMENT FORECAST (${h.currency} millions)`],
    ["Forecast columns are formulas driven by the Assumptions sheet."],
    [],
    header,
  ];
  // pad to the exact row layout we reference above
  while (mRows.length < M.ufcf) mRows.push([...blank]);
  mRows[M.rev - 1] = ["Revenue"]; mRows[M.cogs - 1] = ["Cost of revenue"]; mRows[M.gp - 1] = ["Gross profit"];
  mRows[M.opex - 1] = ["Operating costs (SG&A)"]; mRows[M.ebit - 1] = ["EBIT"]; mRows[M.da - 1] = ["D&A"];
  mRows[M.ebitda - 1] = ["EBITDA"]; mRows[M.taxOnEbit - 1] = ["Tax on EBIT"]; mRows[M.nopat - 1] = ["NOPAT (EBIT after tax)"];
  mRows[M.capex - 1] = ["Capital expenditure"];
  mRows[14] = ["WORKING CAPITAL"];
  mRows[M.ar - 1] = ["Accounts receivable"]; mRows[M.inv - 1] = ["Inventory"]; mRows[M.oca - 1] = ["Other current assets"];
  mRows[M.ap - 1] = ["Accounts payable"]; mRows[M.accr - 1] = ["Accrued expenses"]; mRows[M.ocl - 1] = ["Other current liabilities"];
  mRows[M.nwc - 1] = ["Net working capital"]; mRows[M.dnwc - 1] = ["Change in net working capital"];
  mRows[M.ufcf - 1] = ["Unlevered free cash flow"];
  mRows[3] = header;

  const wsM = XLSX.utils.aoa_to_sheet(mRows);
  wsM["!cols"] = [{ wch: 32 }, ...header.slice(1).map(() => ({ wch: 13 }))];

  // historical columns — real filing values
  const histGp = (i) => h.rev[i] - h.cogs[i];
  const histEbit = (i) => histGp(i) - h.sga[i];
  for (let i = 0; i < nH; i++) {
    const C = col(c0 + i);
    setV(wsM, C + M.rev, r1(h.rev[i]), NUM);
    setV(wsM, C + M.cogs, r1(h.cogs[i]), NUM);
    setV(wsM, C + M.gp, r1(histGp(i)), NUM);
    setV(wsM, C + M.opex, r1(h.sga[i]), NUM);
    setV(wsM, C + M.ebit, r1(histEbit(i)), NUM);
    setV(wsM, C + M.da, r1(h.da[i]), NUM);
    setV(wsM, C + M.ebitda, r1(histEbit(i) + h.da[i]), NUM);
    setV(wsM, C + M.capex, r1(h.capex[i]), NUM);
    setV(wsM, C + M.ar, r1(h.ar[i]), NUM);
    setV(wsM, C + M.inv, r1(h.inv[i]), NUM);
    setV(wsM, C + M.oca, r1(Math.max(h.oca[i], 0)), NUM);
    setV(wsM, C + M.ap, r1(h.ap[i]), NUM);
    setV(wsM, C + M.accr, r1(h.accr[i]), NUM);
    setV(wsM, C + M.ocl, r1(Math.max(h.ocl[i], 0)), NUM);
    setF(wsM, C + M.nwc, `(${C}${M.ar}+${C}${M.inv}+${C}${M.oca})-(${C}${M.ap}+${C}${M.accr}+${C}${M.ocl})`, NUM);
  }

  // forecast columns — every cell a formula
  for (let j = 0; j < nF; j++) {
    const C = col(fc0 + j), P = col(fc0 + j - 1);
    setF(wsM, C + M.rev, `${P}${M.rev}*(1+${AS(A.growth)})`, NUM);
    setF(wsM, C + M.cogs, `${C}${M.rev}*(1-${AS(A.gm)})`, NUM);
    setF(wsM, C + M.gp, `${C}${M.rev}-${C}${M.cogs}`, NUM);
    setF(wsM, C + M.opex, `${C}${M.rev}*${AS(A.opex)}`, NUM);
    setF(wsM, C + M.ebit, `${C}${M.gp}-${C}${M.opex}`, NUM);
    setF(wsM, C + M.da, `${C}${M.rev}*${AS(A.da)}`, NUM);
    setF(wsM, C + M.ebitda, `${C}${M.ebit}+${C}${M.da}`, NUM);
    setF(wsM, C + M.taxOnEbit, `${C}${M.ebit}*${AS(A.tax)}`, NUM);
    setF(wsM, C + M.nopat, `${C}${M.ebit}-${C}${M.taxOnEbit}`, NUM);
    setF(wsM, C + M.capex, `${C}${M.rev}*${AS(A.capex)}`, NUM);
    setF(wsM, C + M.ar, `${C}${M.rev}*${AS(A.ar)}`, NUM);
    setF(wsM, C + M.inv, `${C}${M.cogs}*${AS(A.inv)}`, NUM);
    setF(wsM, C + M.oca, `${C}${M.rev}*${AS(A.oca)}`, NUM);
    setF(wsM, C + M.ap, `${C}${M.cogs}*${AS(A.ap)}`, NUM);
    setF(wsM, C + M.accr, `${C}${M.rev}*${AS(A.accr)}`, NUM);
    setF(wsM, C + M.ocl, `${C}${M.rev}*${AS(A.ocl)}`, NUM);
    setF(wsM, C + M.nwc, `(${C}${M.ar}+${C}${M.inv}+${C}${M.oca})-(${C}${M.ap}+${C}${M.accr}+${C}${M.ocl})`, NUM);
    setF(wsM, C + M.dnwc, `${C}${M.nwc}-${P}${M.nwc}`, NUM);
    setF(wsM, C + M.ufcf, `${C}${M.nopat}+${C}${M.da}-${C}${M.capex}-${C}${M.dnwc}`, NUM);
  }
  XLSX.utils.book_append_sheet(wb, wsM, "Model");

  /* ---------------- 3. DCF (all formulas) ---------------- */
  const D = {
    ke: 4, kdat: 5, mve: 6, debt: 7, we: 8, wd: 9, wacc: 10,
    yr: 13, ufcf: 14, disc: 15, pv: 16,
    sumPv: 18, tv: 19, pvTv: 20, ev: 21, nd: 22, eq: 23, sh: 24, vps: 25, px: 26, up: 27,
    exitTv: 29, exitVps: 30,
  };
  const dRows = [
    [`${h.name} — DISCOUNTED CASH FLOW`],
    ["Every figure below is a formula. Edit the Assumptions sheet to change them."],
    [],
    ["Cost of equity (rf + beta x ERP)"], ["After-tax cost of debt"], ["Market value of equity"],
    ["Total debt"], ["Equity weight"], ["Debt weight"], ["WACC"],
    [], [],
    ["Forecast year", 1, 2, 3, 4, 5],
    ["Unlevered free cash flow"], ["Discount factor"], ["Present value of FCF"],
    [],
    ["Sum of PV (years 1-5)"], ["Terminal value (Gordon growth)"], ["PV of terminal value"],
    ["Enterprise value"], ["Less: net debt"], ["Equity value"], ["Diluted shares (M)"],
    ["Intrinsic value per share"], ["Current share price"], ["Upside / (downside)"],
    [],
    ["Cross-check — exit multiple terminal value"], ["Value per share (exit multiple)"],
  ];
  const wsD = XLSX.utils.aoa_to_sheet(dRows);
  wsD["!cols"] = [{ wch: 36 }, { wch: 15 }, { wch: 13 }, { wch: 13 }, { wch: 13 }, { wch: 13 }];

  setF(wsD, "B" + D.ke, `${AS(A.rf)}+${AS(A.beta)}*${AS(A.erp)}`, PCT);
  setF(wsD, "B" + D.kdat, `${AS(A.kd)}*(1-${AS(A.tax)})`, PCT);
  setF(wsD, "B" + D.mve, `${AS(A.shares)}*${AS(A.price)}`, NUM);
  setF(wsD, "B" + D.debt, `${AS(A.debt)}`, NUM);
  setF(wsD, "B" + D.we, `IF(B${D.mve}+B${D.debt}=0,1,B${D.mve}/(B${D.mve}+B${D.debt}))`, PCT);
  setF(wsD, "B" + D.wd, `1-B${D.we}`, PCT);
  setF(wsD, "B" + D.wacc, `B${D.we}*B${D.ke}+B${D.wd}*B${D.kdat}`, PCT);

  for (let j = 0; j < nF; j++) {
    const C = col(1 + j);                 // B..F on the DCF sheet
    const MC = col(fc0 + j);              // matching forecast column on Model
    setF(wsD, C + D.ufcf, `Model!${MC}${M.ufcf}`, NUM);
    setF(wsD, C + D.disc, `1/(1+$B$${D.wacc})^${j + 1}`, "0.0000");
    setF(wsD, C + D.pv, `${C}${D.ufcf}*${C}${D.disc}`, NUM);
  }
  const lastF = col(1 + nF - 1);
  setF(wsD, "B" + D.sumPv, `SUM(B${D.pv}:${lastF}${D.pv})`, NUM);
  setF(wsD, "B" + D.tv, `${lastF}${D.ufcf}*(1+${AS(A.tg)})/(B${D.wacc}-${AS(A.tg)})`, NUM);
  setF(wsD, "B" + D.pvTv, `B${D.tv}/(1+B${D.wacc})^${nF}`, NUM);
  setF(wsD, "B" + D.ev, `B${D.sumPv}+B${D.pvTv}`, NUM);
  setF(wsD, "B" + D.nd, `${AS(A.debt)}-${AS(A.cash)}`, NUM);
  setF(wsD, "B" + D.eq, `B${D.ev}-B${D.nd}`, NUM);
  setF(wsD, "B" + D.sh, `${AS(A.shares)}`, NUM);
  setF(wsD, "B" + D.vps, `B${D.eq}/B${D.sh}`, "#,##0.00");
  setF(wsD, "B" + D.px, `${AS(A.price)}`, "#,##0.00");
  setF(wsD, "B" + D.up, `B${D.vps}/B${D.px}-1`, PCT);
  setF(wsD, "B" + D.exitTv, `Model!${col(fc0 + nF - 1)}${M.ebitda}*${AS(A.exit)}`, NUM);
  setF(wsD, "B" + D.exitVps, `(B${D.sumPv}+B${D.exitTv}/(1+B${D.wacc})^${nF}-B${D.nd})/B${D.sh}`, "#,##0.00");
  XLSX.utils.book_append_sheet(wb, wsD, "DCF");

  /* ---------------- 4. SUMMARY ---------------- */
  // NOTE: every row carries a second column so the sheet range spans B — otherwise
  // formula cells written into column B fall outside !ref and readers drop them.
  const sRows = [
    [`${h.name} (${h.symbol}) — VALUATION SUMMARY`, null],
    [`${scenName} case · ${h.currency} millions · ${h.exchange || "US-listed"}`, null],
    [null, null],
    ["Intrinsic value per share", null], ["Current share price", null], ["Upside / (downside)", null],
    ["Enterprise value", null], ["WACC", null],
    [null, null],
    ["This workbook is live: edit the Assumptions sheet and every figure recalculates.", null],
    ["Source: company filings via Financial Modeling Prep. Educational tool — not investment advice.", null],
    ["Built with Vexa · hivexa.vercel.app", null],
  ];
  const wsS = XLSX.utils.aoa_to_sheet(sRows);
  wsS["!cols"] = [{ wch: 46 }, { wch: 16 }];
  setF(wsS, "B4", `DCF!B${D.vps}`, "#,##0.00");
  setF(wsS, "B5", `DCF!B${D.px}`, "#,##0.00");
  setF(wsS, "B6", `DCF!B${D.up}`, PCT);
  setF(wsS, "B7", `DCF!B${D.ev}`, NUM);
  setF(wsS, "B8", `DCF!B${D.wacc}`, PCT);
  XLSX.utils.book_append_sheet(wb, wsS, "Summary");
  wb.SheetNames = ["Summary", "Assumptions", "Model", "DCF"];

  const safe = (h.symbol || "model").replace(/[^A-Za-z0-9]/g, "");
  XLSX.writeFile(wb, `Vexa_${safe}_${scenName}_model.xlsx`);
}
